# Generated by Django 5.1.7 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("original_name", models.CharField(blank=True, default="", max_length=255)),
                ("thumb_url", models.URLField(blank=True, default="", max_length=500)),
                ("poster_url", models.URLField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("total_episodes", models.PositiveIntegerField(blank=True, null=True)),
                ("current_episode", models.CharField(blank=True, default="", max_length=100)),
                ("duration", models.CharField(blank=True, default="", max_length=100)),
                ("quality", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                ("director", models.CharField(blank=True, default="", max_length=255)),
                ("casts", models.TextField(blank=True, default="")),
                ("source_created", models.DateTimeField(blank=True, null=True)),
                ("source_modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("category_data", models.JSONField(blank=True, default=dict)),
                ("episodes", models.JSONField(blank=True, default=list)),
                ("format_types", models.JSONField(blank=True, default=list)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("years", models.JSONField(blank=True, default=list)),
                ("format_tags", models.TextField(blank=True, db_index=True, default="")),
                ("genre_tags", models.TextField(blank=True, db_index=True, default="")),
                ("country_tags", models.TextField(blank=True, db_index=True, default="")),
                ("year_tags", models.TextField(blank=True, db_index=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-source_modified", "-updated_at"]},
        ),
    ]
