# Generated by Django 5.1.7 on 2026-03-01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_moviecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="moviecomment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
