# Generated by Django 5.1.7 on 2026-03-01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_movie_rating_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviecomment",
            name="rating",
        ),
        migrations.CreateModel(
            name="MovieFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="movie.movie"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movie_favorites", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("movie", "user")},
            },
        ),
        migrations.CreateModel(
            name="MovieWatchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("episode_slug", models.CharField(blank=True, default="", max_length=255)),
                ("episode_name", models.CharField(blank=True, default="", max_length=100)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("total_seconds", models.PositiveIntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="watch_histories", to="movie.movie"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movie_watch_histories", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-last_watched_at"],
                "unique_together": {("movie", "user")},
            },
        ),
        migrations.CreateModel(
            name="MovieRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("review", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="movie.movie"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movie_ratings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("movie", "user")},
            },
        ),
    ]
