# Generated by Django 5.1.7 on 2026-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('viewer', 'Viewer'), ('moderator', 'Moderator'), ('editor', 'Editor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
